name: "Add Event (EN)"
description: "Add or update event"
title: "[EVENT EN]: "
labels: ["event_en"]
body:
  - type: input
    id: id
    attributes:
      label: "id"
      description: "Unique event ID"
      placeholder: "2026-05-01-community-picnic"
    validations:
      required: true

  - type: input
    id: date
    attributes:
      label: "date"
      placeholder: "2026-05-01"
    validations:
      required: true

  - type: dropdown
    id: actual
    attributes:
      label: "actual"
      options:
        - "false"
        - "true"
    validations:
      required: true

  - type: dropdown
    id: past
    attributes:
      label: "past"
      options:
        - "false"
        - "true"
    validations:
      required: true

  - type: input
    id: title
    attributes:
      label: "title"
      placeholder: "TCS ng Community Picnic"
    validations:
      required: true

  - type: input
    id: flyer
    attributes:
      label: "flyer"
      description: "Path to image"
      placeholder: "./event_imgs/event-3.jpg"
    validations:
      required: true

  - type: input
    id: alt
    attributes:
      label: "alt"
      placeholder: "Flyer: TCS ng Community Picnic"
    validations:
      required: true

  - type: textarea
    id: short
    attributes:
      label: "short"
      placeholder: "Short description of the event"
    validations:
      required: true

  - type: textarea
    id: long
    attributes:
      label: "long"
      placeholder: "Long description of the event"
    validations:
      required: true
